# Generated by Django 4.1 on 2023-02-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameTheory_BI_WebApp', '0002_rows_delete_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowsWeekly',
            fields=[
                ('rows_id', models.AutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=100)),
                ('campaign_network', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('partner', models.CharField(max_length=100)),
                ('os_name', models.CharField(max_length=100)),
                ('week', models.CharField(max_length=100)),
                ('installs', models.IntegerField()),
            ],
        ),
    ]
