# Generated by Django 4.1 on 2023-02-03 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameTheory_BI_WebApp', '0003_rowsweekly'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rows',
            old_name='day',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='rowsweekly',
            old_name='week',
            new_name='date',
        ),
    ]
